### ISSUE TITLE
[FEATURE] Update README with a list of contributors 

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#105]
### What?

Create a section in the README for Contributors

### Why?

Contributors are key for open source projects. I would like to thanks all of them, and make visible as much as possible them.  

### How?

It mush fetch from GitHub the list of contributors. It doesn't make sense to update it each time we have new contributors to the project. It must be dynamic. 

Add the section at the end of the README:
<p align ="center">
<img width="600" alt="image" src="https://github.com/user-attachments/assets/8d377559-5d8e-46fb-a080-443221b4594a">
<p/>

Usually it has a format of a table.

**Comment by Virtual4087** [comment]
I would like to do it

**Comment by Villain45** [comment]
@manuelalferez Just add this

```
<a href="https://github.com/manuelalferez/flowinance/graphs/contributors">
  <img src="https://contrib.rocks/image?repo=manuelalferez/flowinance" />
</a>
```

**Comment by manuelalferez** [comment]
@Villain45 you are the best! I didn't know that one. Feel free to create a PR with that, since it's your merit

**Comment by Virtual4087** [comment]
I pushed a PR @manuelalferez , if @Villain45 doesn't do it, you can merge mine.
