### ISSUE TITLE
[FEATURE] Added horizontal scrolling to the feature section

### ISSUE THREAD

**Issue by Adi21032004** [manuelalferez/flowinance#118]
### What?

 @manuelalferez  

https://github.com/user-attachments/assets/c3abc189-825d-4a91-97fe-7243dcfeb86e

When the user scrolls down the page, the feature cards move right to left where each card scales up at at the center of the screen and scales down as it moves to left. When the user scrolls down, the feature card move towards right and other process remains same. The user cannot move up or down the page until the first card or the last card is reached

### Why?

The feature section is very simple, needed more interactivity for better user experience

### How?

Used GSAP library

**Comment by shawaiz-khan** [comment]
Can I do this?

**Comment by Adi21032004** [comment]
@manuelalferez Please assign this to me

**Comment by manuelalferez** [comment]
Thank you very much for your suggestions. But that part of the page has already been refactored by other flowinance's members: it doesn't make much sense to keep refactoring it forever. Let's leave it as it is, and add value in other parts of the project

**Comment by manuelalferez** [comment]
Feel free to open other issues
