### ISSUE TITLE
Create a Wiki for the project

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#51]
## Description:
We need a Wiki to document key information about the project, making it easier for new contributors and maintainers to get started.

## Tasks:

- Overview: Briefly describe the project and its purpose.
- Setup Instructions: Steps for setting up the project locally.
- Contribution Guidelines: How to contribute (forking, pull requests, etc.).
- Project Structure: Overview of the architecture and main components.
- FAQs/Best Practices: Common questions and troubleshooting tips.

## Goal:
A clear, organized Wiki that helps contributors understand and work on the project.

**Comment by vk-cse** [comment]
i'm ready to fix this issue, pls assign it to me

**Comment by vk-cse** [comment]
sir, I want to know about the issue that I have to make a webpage showing
wiki of ur project or just a markdown file...pls let me know asap so that I
should start working.

**Comment by AfubeAngel** [comment]
Hi @manuelalferez I would love to contribute to this as a technical writer. If there are enhancements or additions needed, please let me know

**Comment by manuelalferez** [comment]
@vk-cse @AfubeAngel, this is the URL for the project Wiki: https://github.com/manuelalferez/flowinance/wiki. Please check if you can edit it and create pages. If you encounter any issues, I can grant you access

**Comment by vk-cse** [comment]
@manuelalferez thank you for this. will update you asap

**Comment by AfubeAngel** [comment]
@manuelalferez Thank you for the opportunity. I'll go through it and give update

**Comment by AfubeAngel** [comment]
@manuelalferez I tried to push the homepage skeleton after cloning the wiki but it appears I do not have permission to. 

remote: Permission to manuelalferez/flowinance.wiki.git denied to AfubeAngel.
fatal: unable to access 'https://github.com/manuelalferez/flowinance.wiki.git/': The requested URL returned error: 403

**Comment by AfubeAngel** [comment]
This is what I have at the moment in my forked repo
![image](https://github.com/user-attachments/assets/b46bac6e-fea4-4403-827d-d2d8f33c5ec1)

**Comment by manuelalferez** [comment]
@AfubeAngel what an awesome work!! I have changed the configuration of the repo, now you should be able to edit the Wiki

**Comment by AfubeAngel** [comment]
@manuelalferez Thnak you. I have been able to edit the wiki. I would need you to please review to ensure accuracy of information, any corrections to be made or additions needed. In the mean time, I'll go ahead to start drafting the contribution guidelines (if that is alright).

Please for the sake of the hacktoberfest, can I create an issue and raise a pull request for this? Thank you again

**Comment by manuelalferez** [comment]
@AfubeAngel Sure! Open a PR for that. I don't know how the CONTRIBUTING.md could be improved, I would like to have it like it's now; simple and easy to read. Maybe you could come up with some ideas with the [README.md](https://github.com/manuelalferez/flowinance/blob/main/README.md), since it's the first thing contributors see when they enter to the repo, it would be nice to have some improvements there. Any idea is welcome @AfubeAngel! I would check out the Wiki now. Thanks!!
