### ISSUE TITLE
[FEATURE] Add some hover effects to Features part

### ISSUE THREAD

**Issue by TheSoumenMondal** [manuelalferez/flowinance#52]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The cards which are in the Features section should have some hover effects for better user experience.

### Proposed Solution

**This part can be improved by adding some more effects and micro-interactions** 

### Do you want to work on this issue?

Yes

**Comment by manuelalferez** [comment]
Sounds good @TheSoumenMondal. Go for it! Let me know if I can assist you with anything

**Comment by TheSoumenMondal** [comment]
Please add one more gssoc label

**Comment by manuelalferez** [comment]
For what is the _gssoc_ tag for?
