### ISSUE TITLE
[FEATURE] Configure Google Oauth for easy signup and signin access. 

### ISSUE THREAD

**Issue by VarunChopra11** [manuelalferez/flowinance#54]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

I'm always frustrated when i see websites asking me my "email" and "create password" rather when websites can implement google oauth for the seamless login, signup and signin.

### Proposed Solution

I request to get this feature implementation assigned to me to get seamless login experience for the user, implementing google oauth and configuration of cookies in users device to refrain from again and again signin.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

i will use google oauth for google authentication.

**Comment by manuelalferez** [comment]
Thank you for your feature request and the detailed explanation @VarunChopra11! I appreciate your enthusiasm to improve the login experience.

However, all authentication for this project is currently handled by Supabase, where our database is also hosted. This setup keeps everything centralized, making it simpler and more convenient to manage both auth and data in one place. Having a unified system reduces complexity, and Supabase provides a reliable and secure auth solution that integrates seamlessly with the rest of the project.

Additionally, I'm personally trying to avoid Google services as much as possible, and I prefer to offer alternatives that respect privacy. That said, I really appreciate your initiative—if you have other ideas I’d be happy to discuss them!
