### ISSUE TITLE
[BUG] Transactions add page not responsive in smaller screens

### ISSUE THREAD

**Issue by revanthnetha** [manuelalferez/flowinance#55]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Description

The current implementation of the Transactions Add page does not display properly on smaller screens (e.g., mobile devices). Elements are not arranged to fit within the viewport, resulting in a poor user experience.

Expected Behavior:
The Transactions Add page should be fully responsive, ensuring that all input fields, buttons, and information are easily accessible and visually appealing on smaller screens.

Environment:

Browser: (e.g., Chrome, Firefox)
Device: (e.g., iPhone, Android phone)
Screen Size: (e.g., 320px width)

### Steps to Reproduce

Include any relevant details like:

- Go to Transactions tab 
-  Click on +Add section
-  You will see that the add page in mobile screen is not responsive.

### Screenshots

![image](https://github.com/user-attachments/assets/7fab9395-3789-4002-b7c7-261f24295ab3)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Reason for not responsive : Either padding or margin not set correctly
Proposed Solution: I'll change the padding to make it responsive and If needed, I can also make the table to look like stack in smaller screens so that it would be neat.

**Comment by revanthnetha** [comment]
Could you please add the label Hactober fest and check the pull request. Happy to change the table look like stack in smaller screens :)

**Comment by manuelalferez** [comment]
Absolutely, you're right @revanthnetha! Flowinance wasn't initially responsive because it was mainly designed for desktop use, but it would be great to make it work smoothly on phones as well. Thanks again for bringing this up—I'll review your PR within the next 3 days
