### ISSUE TITLE
[BUG] Prevent users from deleting the demo account in account settings

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#59]
### Description

In the demo account, users can interact with the application, but they have the ability to delete the account in the settings, which isn't ideal.

### Steps to Reproduce

Include any relevant details like:

- **Page**: Account settings
- **Objective**: We want to prevent users from accidentally deleting the demo account by hiding that option, as shown in the screenshot.
- **Issue**: Users can mistakenly remove the demo account.

### Screenshots

<img width="1195" alt="image" src="https://github.com/user-attachments/assets/bbd9f372-fb2b-458d-8aa6-d5deed48b8d1">

### Proposed Solution
A possible solution could be to detect if the email is the demo account email, taking it from the env variables, and hide that option in the settings.

### Do you want to work on this issue?

No

**Comment by babyo77** [comment]
i can do that

**Comment by Srijan25** [comment]
is the work done or i can start. please assign it to me

**Comment by manuelalferez** [comment]
Hey @Srijan25, @babyo77 is currently working on this issue in the following PR: [#60](https://github.com/manuelalferez/flowinance/pull/60)
