### ISSUE TITLE
[FEATURE] Animation In Landing Page

### ISSUE THREAD

**Issue by ppranay20** [manuelalferez/flowinance#63]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

The request for adding animation functionality addresses the need for a more engaging and dynamic user experience. Currently, the website lacks interactive visual elements, making it feel static and less engaging for users.

### Proposed Solution

The animation will enhance the website and improve user experience.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I will use framer-motion to add animation.

**Comment by manuelalferez** [comment]
Hi @ppranay20! Could you share more about the animations you're planning to add and where you intend to implement them? I’d love to get a clearer perspective on your ideas. Thanks!

**Comment by manuelalferez** [comment]
Before you get started, please take a moment to read the contributing guidelines: [Contributing Guide](https://github.com/manuelalferez/flowinance/blob/main/CONTRIBUTING.md).

**Comment by ppranay20** [comment]
The idea of having animation I got from this website https://preview.uideck.com/items/appvilla

**Comment by manuelalferez** [comment]
Looks good! If you find any other animations for the page, that would be nice, especially for the images currently static, it would be cool
