### ISSUE TITLE
[FEATURE] Export transactions as csv

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#72]
### What?

The users have their transactions uploaded and categorized. Wouldn't it be great if they could export their transactions as a CSV file?

### Why?

In the event of a database issue or any other problem, users will have their data backed up. This allows them to easily upload their data elsewhere and facilitates migration between platforms.

### How?

The goal is to retrieve all the transactions of the user and create a CSV file. Implement a modal for this feature, similar to how modals are used in Flowinance, for example, when the user clicks to delete a transaction ([reference](https://github.com/manuelalferez/flowinance/blob/d5316f73f836c83eb389caff4a62d26f97e74b11/src/app/transactions/ui/transactions-table.tsx#L234-L247)). Consider displaying a loading animation in the modal while the file is being generated, along with a "Download" button that appears when it's ready.

Something like this:  

<p align="center">
  <img width="800" alt="image" src="https://github.com/user-attachments/assets/f86b632c-b95e-430d-bb0d-41ffb8c713d6">
</p>

### Where? 
https://flowinance.com/account/settings

Related with: #73

**Comment by vizzv** [comment]
@manuelalferez I am amazed by product idea and want to contribute to it.
Can you please assign me.I will also apply for assign for #73 as both logic can be reused .
