### ISSUE TITLE
[FEATURE] Easy demo access 

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#75]
### What?

Currently, users have to copy and paste the credentials to enter the demo. It would be better to have a button on the landing page to access the demo account directly

### Why?

The current login system for the demo isn't user-friendly; it's too much work

### How?

1. **Delete the information on the sign-in page:**  
   <p align="center">
       <img width="400" alt="image" src="https://github.com/user-attachments/assets/deb7435c-312f-45d2-8fb2-020facf44928">
   </p>

2. **Add a button on the landing page** that automatically redirects to the dashboard with the demo account login.

**Comment by Villain45** [comment]
Ok will be doing that, can you assign it to me?

**Comment by Villain45** [comment]
why was .env.example removed from repo? @manuelalferez

**Comment by manuelalferez** [comment]
@Villain45 thanks for taking that into account! It was removed here: https://github.com/manuelalferez/flowinance/commit/869789e957dd522b80381d4afd2d1ce8a8f6a763. I will added it back

**Comment by Villain45** [comment]
In #78 it is added by the way, you can just merge the PR

**Comment by Villain45** [comment]
@manuelalferez you can close this issue, just saw this open on my dashboard
