### ISSUE TITLE
[BUG] New User Confirmation Link Redirects to Localhost Instead of Actual Domain

### ISSUE THREAD

**Issue by NishantCoder108** [manuelalferez/flowinance#80]
### Verify this issue hasn't been reported before

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### What

When a new user signs up, they receive an email with a confirmation link. After clicking the confirmation link, they are redirected to localhost instead of the actual domain URL, such as https://flowinance.com/.

### Steps to Reproduce

After signing up, you'll receive a confirmation link on mail. When you click the link, it redirects to localhost instead of the actual live URL.

### Do you want to work on this issue?

No

**Comment by manuelalferez** [comment]
@NishantCoder108 thanks for noticing it!! It might be related with the supabase configuration. I will take care of it

**Comment by manuelalferez** [comment]
Copying here the conversation that started on Discord: 
>NishantTechie —
Hi @manuelalferez ,
I was trying to reach Upload ai section , unfortunately i was not able  to login in localhost, i face issues related verification mail , so i setup  supabase , for mail provider resend  and add domain to send verification mail , but resend is taking lots of time to verify dns ,that i setup with godaddy dns provider.
>
>During exploring , i saw some issues, that could be fix:
>- When new user signup ,after clicking on confirmation link , they are redirecting to localhost instead of actual domain url like https://flowinance.com/ .
>- If they are already user , so they must be notify on ui screen, you must be login . but here notification is not coming on screen instead they are follow signup flow.
>- Upload Ai  api is not working well (Internal server error) https://flowinance.com/transactions/upload-ai

**Comment by manuelalferez** [comment]
@NishantCoder108 I have fixed the issue with the confirmation URL:
<p align="center">
<img width="600" alt="image" src="https://github.com/user-attachments/assets/8957dbe8-c3fe-492c-a4ab-1f9f161d54ba">
<p/>
