### ISSUE TITLE
[FEATURE] Make features section interactive

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#81]
### What?

Make features section in the Landing page interactive and more attractive. 
<p align="center">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/e50b8e4f-b3d1-4788-a690-083d8abe234b">
</p>

### Why?

It's very static and it's calling zero the attention of the users. 

### How?

Open to ideas. Please, feel free to discuss, share them in this issue and come up with ideas to improve this.

**Comment by Adi21032004** [comment]
I can do this.

**Comment by Adi21032004** [comment]
@manuelalferez can you pls give idea about how much interactivity you want

**Comment by ppranay20** [comment]
How is this design?

https://github.com/user-attachments/assets/a190823e-e581-4260-805c-b3869fbdf2ea

**Comment by manuelalferez** [comment]
@ppranay20 it looks nice! Since you are the only one who proposed one example, awarded!
