### ISSUE TITLE
[FEATURE] Visualize savings in the Dashboard page

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/flowinance#83]
### What?

For now, the savings of the users are not being displayed in the Dashboard. 

<p align="center">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/5a99314f-b7de-44a9-8036-297605148d24">
</p>

### Why?

The users are making their transaction as Savings, but they are never visualized. 

### How?

Create a section on the dashboard for the savings. 

<p align="center">
<img width="400" alt="image" src="https://github.com/user-attachments/assets/41b62c80-8065-440a-90a6-95cfd5021334">
</p>

Use the appropriate icon to match the overall design: https://icones.js.org/collection/all

**Comment by revanthnetha** [comment]
Could you assign this issue to me.I can work on this. @manuelalferez
