### ISSUE TITLE
[FEATURE] Skeleton for Dashboard Page

### ISSUE THREAD

**Issue by revanthnetha** [manuelalferez/flowinance#84]
### What?

While the Initial Loading of Dashboard Page, There is spinner for loading. But It would be more appealing if skeleton is shown while loading the page.

 

### Why?

Example Skeleton Card for reference:

![image](https://github.com/user-attachments/assets/ce384c06-0bcd-464a-9254-1b940c104e68)

Reason :  So that It creates more intuitive for users that something of charts is coming up.

### How?

Implemention Skeleton using Tailwind CSS - animate pulse

**Comment by ppranay20** [comment]
Can I work in this issue?

**Comment by manuelalferez** [comment]
I love this feature! @ppranay20 go ahead with it! Since @revanthnetha created it, I don't know if he/she is already working on it

**Comment by revanthnetha** [comment]
Sorry to say but But I'm already working on this issue @ppranay20  @manuelalferez
