### ISSUE TITLE
[BUG] Module not found: Can't resolve '@supabase/supabase-js' 

### ISSUE THREAD

**Issue by Shailendra1703** [manuelalferez/flowinance#92]
### Verify this issue hasn't been reported before

- [ ] I have checked "open" AND "closed" issues and this is not a duplicate

#### By default when we use `npm install` this additional dependency is not installed 

![image](https://github.com/user-attachments/assets/a5081458-d54f-4972-acf2-286e3508badf)

### Steps to Reproduce

- clone the project
- run `npm install`
- run `npm run dev`

### Do you want to work on this issue?

Yes

**Comment by Shailendra1703** [comment]
### Solution : ` npm i @supabase/supabase-js`

**Comment by manuelalferez** [comment]
@Shailendra1703 this issue was discussed here: https://github.com/manuelalferez/flowinance/pull/56#issuecomment-2399968838

Today I will be working on improving the documentation in this matter. Thanks for bring it up!
